[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv .venv",
  ". .venv/bin/activate",
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
cmd = "bash start.sh"

[metadata]
watch = false
